// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: etymologies.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createEtymology = `-- name: CreateEtymology :one
INSERT INTO etymologies (id, word, etymology, pos)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, word, etymology, pos
`

type CreateEtymologyParams struct {
	ID        uuid.UUID
	Word      string
	Etymology string
	Pos       string
}

func (q *Queries) CreateEtymology(ctx context.Context, arg CreateEtymologyParams) (Etymology, error) {
	row := q.db.QueryRowContext(ctx, createEtymology,
		arg.ID,
		arg.Word,
		arg.Etymology,
		arg.Pos,
	)
	var i Etymology
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.Etymology,
		&i.Pos,
	)
	return i, err
}
