// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lemmas.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createLemma = `-- name: CreateLemma :one
INSERT INTO lemmas (id, word, lemma, pos, etymology_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, word, lemma, pos, etymology_id
`

type CreateLemmaParams struct {
	ID          uuid.UUID
	Word        string
	Lemma       string
	Pos         string
	EtymologyID uuid.UUID
}

func (q *Queries) CreateLemma(ctx context.Context, arg CreateLemmaParams) (Lemma, error) {
	row := q.db.QueryRowContext(ctx, createLemma,
		arg.ID,
		arg.Word,
		arg.Lemma,
		arg.Pos,
		arg.EtymologyID,
	)
	var i Lemma
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.Lemma,
		&i.Pos,
		&i.EtymologyID,
	)
	return i, err
}

const getLemma = `-- name: GetLemma :one
SELECT id, word, lemma, pos, etymology_id FROM lemmas 
WHERE word = $1
`

func (q *Queries) GetLemma(ctx context.Context, word string) (Lemma, error) {
	row := q.db.QueryRowContext(ctx, getLemma, word)
	var i Lemma
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.Lemma,
		&i.Pos,
		&i.EtymologyID,
	)
	return i, err
}
