// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: master.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createMaster = `-- name: CreateMaster :one
INSERT INTO master (id, word, lemma, pos, etymology_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, word, lemma, pos, etymology_id
`

type CreateMasterParams struct {
	ID          uuid.UUID
	Word        string
	Lemma       string
	Pos         string
	EtymologyID uuid.UUID
}

func (q *Queries) CreateMaster(ctx context.Context, arg CreateMasterParams) (Master, error) {
	row := q.db.QueryRowContext(ctx, createMaster,
		arg.ID,
		arg.Word,
		arg.Lemma,
		arg.Pos,
		arg.EtymologyID,
	)
	var i Master
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.Lemma,
		&i.Pos,
		&i.EtymologyID,
	)
	return i, err
}

const getMaster = `-- name: GetMaster :one
SELECT id, word, lemma, pos, etymology_id FROM master
WHERE word = $1
`

func (q *Queries) GetMaster(ctx context.Context, word string) (Master, error) {
	row := q.db.QueryRowContext(ctx, getMaster, word)
	var i Master
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.Lemma,
		&i.Pos,
		&i.EtymologyID,
	)
	return i, err
}
