// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/google/uuid"
)

type Etymology struct {
	ID        uuid.UUID
	Word      string
	Etymology string
	Pos       string
}
