// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/google/uuid"
)

type Etymology struct {
	ID        uuid.UUID
	Word      string
	Etymology string
	Pos       string
}

type Lemma struct {
	ID          uuid.UUID
	Word        string
	Lemma       string
	Pos         string
	EtymologyID uuid.UUID
}

type Master struct {
	ID          uuid.UUID
	Word        string
	Lemma       string
	Pos         string
	EtymologyID uuid.UUID
}
